services:
  web:
    container_name: hhweb
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web:/data/web
      - ./web/static/:/var/www/hobbyhunter/static/
    environment:
      DEBUG: 'true'
    command: bash -c "/data/web/entrypoint.sh"
    depends_on:
      - db  # Add this line to indicate that the 'web' service depends on the 'db' service

  nginx:
    container_name: hhnginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
  db:
    container_name: postgresdb
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      TZ: UTC
    ports:
      - "5432:5432"  # Map PostgreSQL port to the host