# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('search', models.CharField(max_length=650, primary_key=True, serialize=False)),
                ('endPoints', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='merchantPages',
            fields=[
                ('merchant', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('endPoints', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('pageId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('stars', models.IntegerField(null=True)),
                ('createdOn', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('averageCost', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('country', models.CharField(max_length=2)),
                ('mainImage', models.FileField(default='no-img.jpg', null=True, upload_to='merchant/main/')),
                ('secondaryImage', models.FileField(default='no-img.jpg', null=True, upload_to='merchant/secondary/')),
                ('ThirdImage', models.FileField(default='no-img.jpg', null=True, upload_to='merchant/third/')),
                ('merchant', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
    ]
