# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:45
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mainImage_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='avatars'),
        ),
    ]
