# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_page_mainimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='mainImage_thumbnail',
        ),
    ]
