# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantEndpointLink',
            fields=[
                ('merchant', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('endPoints', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageId', models.CharField(max_length=400, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('sessions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('users', jsonfield.fields.JSONField()),
                ('pub', models.CharField(default='', max_length=1024)),
                ('priv', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SessionEndpoint',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('spots', models.IntegerField(default=-1)),
                ('datetime', models.DateTimeField(null=True)),
                ('pageId', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
